Installing Pandas

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\myaqo\AppData\Roaming\Python\Python312\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\myaqo\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\myaqo\AppData\Roaming\Python\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\myaqo\AppData\Roaming\Python\Python312\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\myaqo\AppData\Roaming\Python\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

Importing Pandas

In [1]:
import pandas as pd

Pandas Version

In [2]:
pd.__version__

'3.0.3'

Importing CSV Files

In [53]:
df = pd.read_csv("IRIS.csv")

Checking Data Frame

In [54]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

If you want to give columns names than used this way

In [ ]:
#df = pd.read_csv("IRIS.csv", names = ['Lenght', 'height'])

In [ ]:
#df

                                            Lenght          height
sepal_length sepal_width petal_length  petal_width         species
5.1          3.5         1.4                   0.2     Iris-setosa
4.9          3           1.4                   0.2     Iris-setosa
4.7          3.2         1.3                   0.2     Iris-setosa
4.6          3.1         1.5                   0.2     Iris-setosa
...                                            ...             ...
6.7          3           5.2                   2.3  Iris-virginica
6.3          2.5         5                     1.9  Iris-virginica
6.5          3           5.2                     2  Iris-virginica
6.2          3.4         5.4                   2.3  Iris-virginica
5.9          3           5.1                   1.8  Iris-virginica

[151 rows x 2 columns]

In [55]:
df.isnull() # The false indicate as their is no null value

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

Using a quick way to check Null Values

In [56]:
df.isnull().sum() # No null value in this dataset present

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [57]:
df.info()
# It tell us about the class in which it is 
# Range from starting to ending
# Non Null count

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

Accessing First 5 rows

In [58]:
print("First 5 rows: ")
df.head()# First 5 rows 
# You can also see as many rows as you want with the command df.head(Your_Number).

First 5 rows:

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Last 5 Rows

In [59]:
df.tail() # Last 5 rows
# You can also see as many rows as you want with the command df.tail(Your_Number).

     sepal_length  sepal_width  petal_length  petal_width         species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

Total number of rows and column in the dataset

In [60]:
df.shape

(150, 5)

A quick stats about the dataset

In [61]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

To handle missing values

In [62]:
df.dropna(inplace= True) # It drop the rows having NaN
# The inplace true is important so that we kept our data upate

In [63]:
df.dropna(inplace= True, axis = 1)  # It drop columns having missing values

Dropping specific rows

In [ ]:
# df.dropna(subset= ['sepal_lenght'], inplace= True)

In [64]:
df.fillna(0)  # Fill missing values with constant if you dont want to drop

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

If there are unsual values or number than

In [66]:
# For example -- This is just an example, the original dataset is fine 
#df.loc[0, 'sepal_length'] = 5
#df

In [ ]:
# Just for an demo it is : 
#for x in df.index:
#    if(df.loc[x, 'sepal_length'])> 5:
#        df.loc[x, 'sepal_length'] = 5

Checking Duplicate values

In [67]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

Checking Total duplicate values

In [68]:
df.duplicated().sum()

np.int64(3)

Removing Duplicate values

In [69]:
df.drop_duplicates(inplace= True)

In [71]:
df.duplicated().sum()

np.int64(0)